{% extends "email/base.html" %}
{% load email_utils %}
{% load data_capture %}

{% block content %}
<p>
  We're emailing regarding the Region 10 CALC data upload <b>#{{ upload_source.id }}</b>, uploaded by <b>{{ upload_source.submitter.email }}</b> on <b>{{ upload_source.created_at|tz_timestamp }}</b>.
</p>
<p>
  Unfortunately, an <b>error occurred</b> while importing the data.
</p>
  {% cta url=r10_upload_link action_text="Try uploading again" %}
<p>
  The traceback below may help the development team debug the problem.
</p>
<pre>
  {{ traceback }}
</pre>
{% endblock %}
